// Code generated by DDL2STRUCT. DO NOT EDIT.
// InputFile: tests/example.sql
package tests

//  aaa.go
type Ddl2Struct struct {
	PersonId  int64  `json:"person_id" gorm:"column:person_id"`   // "ID"
	It        int64  `json:"it" gorm:"column:it"`                 // "id"
	Tit       int8   `json:"tit" gorm:"column:tit"`               // "tinyint"
	LastName  string `json:"last_name" gorm:"column:last_name"`   // "last Name"
	FirstName string `json:"first_name" gorm:"column:first_name"` // "first Name"
	Address   string `json:"address" gorm:"column:address"`       // "address"
	City      string `json:"city" gorm:"column:city"`             // "city"
}

func (Ddl2Struct) TableName() string {
	return "ddl2struct"
}
