// Code generated by DDL2STRUCT. DO NOT EDIT.
// InputFile: tests/example.sql
package tests

type Ddl2Struct2 struct {
	PersonId  int    `json:"person_id" gorm:"column:person_id"`
	LastName  string `json:"last_name" gorm:"column:last_name"`
	FirstName string `json:"first_name" gorm:"column:first_name"`
	Address   string `json:"address" gorm:"column:address"`
	City      string `json:"city" gorm:"column:city"`
}

func (Ddl2Struct2) TableName() string {
	return "ddl2struct2"
}
