package tpl

var TableTemplate = `// Code generated by DDL2STRUCT. DO NOT EDIT.
// InputFile: {{ .InputFile }}
package {{ .PackageName}}

{{- if mapExists . }}
import (
	{{- range $alias, $path := .Imports}}
	{{- if eq $alias $path }}
	"{{$path}}"
	{{- else }}
	{{$alias }}"{{$path}}"
	{{- end }}
	{{- end}}
)
{{- end }}


{{- range $tableName, $table := .Structs}}
{{ if $table.TableComment }} // {{ $table.TableComment }} {{- end}}
type {{ ToCamel $tableName }} struct{
	{{- range $idx, $column := $table.Columns}}
	{{ ToCamel $column.Name }} {{ $column.Type }}  ` + "`json:\"{{ ToSnake $column.Name }}\" gorm:\"column:{{ $column.Name }}\"`" + `{{ if $column.Comment }}// {{ $column.Comment }}  {{- end}}
	{{- end}}
}

func ({{ ToCamel $tableName }}) TableName() string {
	return "{{ $tableName }}"
}
{{- end}}
`
