package tpl

var TableTemplate = `// Code generated by DDL2STRUCT. DO NOT EDIT.
// InputFile: {{ .InputFile }}
package {{ .PackageName}}

{{- if mapExists . }}
import (
	{{- range $alias, $path := .Imports}}
	{{- if eq $alias $path }}
	"{{$path}}"
	{{- else }}
	{{$alias }}"{{$path}}"
	{{- end }}
	{{- end}}
)
{{- end }}


{{- range $tableName, $columns := .Structs}}
type {{ ToCamel $tableName }} struct{
	{{- range $idx, $column := $columns}}
	{{ ToCamel $column.Name }} {{ $column.Type }}  ` + "`json:\"{{ ToSnake $column.Name }}\" gorm:\"column:{{ $column.Name }}\"`" + `
	{{- end}}
}

func ({{ ToCamel $tableName }}) TableName() string {
	return "{{ $tableName }}"
}
{{- end}}
`
