package tpl

var TableTemplate = `// Code generated by DDL2STRUCT. DO NOT EDIT.
// InputFile: {{ .InputFile }}
package {{ .PackageName}}

{{- if mapExists . }}
import (
	{{- range $alias, $path := .Imports}}
	{{- if eq $alias $path }}
	"{{$path}}"
	{{- else }}
	{{$alias }}"{{$path}}"
	{{- end }}
	{{- end}}
)
{{- end }}

{{ .FileContent }}
`
