package cmd

import (
	"fmt"
	"io/ioutil"
	"os"

	"github.com/Sterrenhemel/ddl2struct/pkg/parser"
	_ "github.com/Sterrenhemel/ddl2struct/pkg/parser_driver"

	"github.com/spf13/cobra"
)

var cfgFile string
var (
	inputPath   string
	outputPath  string
	packageName string
)

var rootCmd = &cobra.Command{
	Use:   "ddl2struct",
	Short: "create golang struct from ddl",
	Long:  ``,
	Run:   runCommand,
}

func Execute() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

func init() {
	flag := rootCmd.PersistentFlags()
	flag.StringVarP(&inputPath, "input", "i", "", `sql file path`)
	flag.StringVarP(&outputPath, "output", "o", "", `output file path`)
	flag.StringVarP(&packageName, "package", "p", "", "go file package")
}

func runCommand(cmd *cobra.Command, args []string) {
	sql, err := ioutil.ReadFile(inputPath)
	if err != nil {
		panic(err)
	}

	var isDir bool
	s, err := os.Stat(outputPath)
	if err != nil {
		isDir = false
	} else {
		if s.IsDir() {
			isDir = true
		} else {
			isDir = false
		}
	}

	parser := parser.New(inputPath, outputPath, isDir, packageName)
	if err := parser.Parse(string(sql)); err != nil {
		panic(err)
	}

	structFiles, err := parser.ToStructs(true)
	if err != nil {
		panic(err)
	}

	for fileName, fileBytes := range structFiles {
		content := fmt.Sprintf(`// Code generated by DDL2STRUCT. DO NOT EDIT.
// InputFile: %s
package %s

%s

`, inputPath, packageName, fileBytes)
		if fileName != "" {
			if err := ioutil.WriteFile(fileName, []byte(content), 0644); err != nil {
				panic(err)
			}
		}
		fmt.Printf("%s", content)
	}
}

func generateFileFromBytes(structBytes []byte) {
	if err := ioutil.WriteFile(outputPath, structBytes, 0644); err != nil {
		panic(err)
	}
}
